from __future__ import annotations

import shutil
import zipfile
from datetime import datetime
from hashlib import sha256
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
LOCALIZATION_ROOT = ROOT / "HXSS_Korean_Localization"
MAINTENANCE_ROOT = LOCALIZATION_ROOT / "MaintenanceKit"
BEPINEX_TEMPLATE = LOCALIZATION_ROOT / "BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.755+3fab71a"
PLUGIN_SOURCE = LOCALIZATION_ROOT / "03_Font_Work" / "Font" / "HuiWenFontReplacer"
PLUGIN_RELEASE_DLL = PLUGIN_SOURCE / "bin" / "Release" / "HXSS.HuiWenFontReplacer.dll"
LIVE_PLUGIN_DIR = ROOT / "BepInEx" / "plugins" / "HXSS.HuiWenFontReplacer"
LIVE_CONFIG = ROOT / "BepInEx" / "config" / "hxss.huiwen-font-replacer.cfg"
PACKAGE_ROOT = LOCALIZATION_ROOT / "ReleasePackages"


VERSION = "v0.1.3"


README_TEXT = """# HuaXia: Warring States Korean Patch

이 패키지는 화하: 전국시대 한국어 패치와 유지보수 자료를 함께 포함한 공개 배포 패키지다.

## 설치

1. 배포 ZIP 압축 해제.
2. Steam 라이브러리에서 Huaxia: Warring States 우클릭.
3. 관리 > 로컬 파일 보기 선택.
4. ZIP 내부 파일과 폴더를 게임 설치 폴더 최상위에 복사.
5. 같은 파일명이 있으면 덮어쓰기.
6. 게임 실행.
7. 언어 설정에서 한국어 선택.
8. 게임 재시작.

복사 대상 폴더는 `hxss.exe`가 있는 폴더다.

## 제거

게임 설치 폴더에서 다음 항목을 삭제한다.

```text
BepInEx/plugins/HXSS.HuiWenFontReplacer/
BepInEx/config/hxss.huiwen-font-replacer.cfg
```

다른 BepInEx 플러그인을 사용하지 않는 경우에만 BepInEx 기반 파일 전체 삭제를 검토한다.
문제가 남아 있으면 Steam에서 게임 파일 무결성 검사를 실행한다.

## 포함 내용

- BepInEx IL2CPP 6.0.0-be.755 기반 파일
- 한국어 패치 플러그인
- 한국어/중국어 병합 폰트
- 한국어 Lua 언어 테이블
- 미번역 UI 보정 사전
- 유지보수 키트
- 한국어 패치 플러그인 소스
- 용어집 및 번역 톤 문서

## 설정

설정 파일 위치:

```text
BepInEx/config/hxss.huiwen-font-replacer.cfg
```

기본값:

- EnableFontReplacement = true
- EnableTextOverrides = true
- EnableChineseCollector = false
- EnableLuaLoadTrace = false
- UiScanIntervalSeconds = 2

미번역 중국어 수집은 배포 기본값에서 꺼져 있다.
수집이 필요한 유지보수자는 EnableChineseCollector 값을 true로 바꾼 뒤 게임을 재시작한다.
수집 결과는 BepInEx/plugins/HXSS.HuiWenFontReplacer/collected_chinese.tsv에 기록된다.

## 유지보수 작업

유지보수 도구 위치:

```text
HXSS_Korean_Localization/MaintenanceKit/
```

기준 번역 파일:

```text
HXSS_Korean_Localization/MaintenanceKit/input/Full_Translation.tsv
```

게임 업데이트 후 변경점 확인:

```text
HXSS_Korean_Localization/MaintenanceKit/update_audit.bat
```

생성되는 주요 리포트:

```text
HXSS_Korean_Localization/MaintenanceKit/output/Update_Summary.tsv
HXSS_Korean_Localization/MaintenanceKit/output/Needs_Translation.tsv
HXSS_Korean_Localization/MaintenanceKit/output/Added_Rows.tsv
HXSS_Korean_Localization/MaintenanceKit/output/Changed_TextOnly.tsv
```

신규 또는 변경 번역 반영:

1. `output/Needs_Translation.tsv`의 `ko_new` 칸을 채운다.
2. `apply_report.bat`을 실행해 `input/Full_Translation.tsv`에 병합한다.
3. `build_patch_lua.bat`을 실행해 패치 Lua를 재생성한다.
4. 게임에서 확인한다.

`Full_Translation.tsv`를 직접 수정한 경우에는 2번을 건너뛰고 `build_patch_lua.bat`만 실행해도 된다.

유지보수 키트에는 Lua 5.4 실행 파일, luac, 암복호화 스크립트가 포함되어 있다.
일반적으로 별도 Lua 설치가 필요 없다.

플러그인 소스 위치:

```text
HXSS_Korean_Localization/03_Font_Work/Font/HuiWenFontReplacer/
```

플러그인 기능을 수정하려면 .NET SDK 환경에서 해당 프로젝트를 빌드한 뒤 DLL을 교체한다.

## 주의

- 게임 업데이트 후 일부 문구가 원문으로 보일 수 있다.
- 기존 게임 파일을 직접 수정하지 않는다.
- 다른 BepInEx 플러그인과 함께 사용할 경우 충돌 가능성이 있다.
- 콘솔에서 한글 또는 중국어가 물음표로 보이면 해당 출력을 번역 파일에 복사하지 않는다.
"""


CONFIG_TEXT = """## Settings file was generated by plugin HXSS HuiWen Font Replacer v0.1.3
## Plugin GUID: hxss.huiwen-font-replacer

[General]

## Replace the HuiWenZhengKai brush font with the bundled Korean/Chinese merged font.
# Setting type: Boolean
# Default value: true
EnableFontReplacement = true

## Apply hardcoded_text.tsv replacements for UI strings that are not covered by the Lua language tables.
# Setting type: Boolean
# Default value: true
EnableTextOverrides = true

[Collector]

## Collect untranslated Chinese UI strings to collected_chinese.tsv after Korean title-start text is detected. Keep disabled for normal play/release.
# Setting type: Boolean
# Default value: false
EnableChineseCollector = false

[Debug]

## Write lua_loader_trace.tsv entries when language Lua files are redirected. Useful only for maintenance debugging.
# Setting type: Boolean
# Default value: false
EnableLuaLoadTrace = false

[Performance]

## Seconds between lightweight UI scans for font replacement and hardcoded UI overrides.
# Setting type: Single
# Default value: 2
UiScanIntervalSeconds = 2
"""


def copytree_clean(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def copy_required_file(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def latest_lua_patch_dir() -> Path:
    installed = LIVE_PLUGIN_DIR / "KoreanPatch"
    if installed.exists():
        return installed
    release_root = LOCALIZATION_ROOT / "01_XML_Localization" / "XmlWork" / "Release"
    candidates = sorted(
        [p for p in release_root.glob("LuaConfig_KO_PluginPatch_*") if (p / "lua").exists()],
        key=lambda p: p.name,
    )
    if not candidates:
        raise FileNotFoundError("No KoreanPatch lua directory found.")
    return candidates[-1] / "lua"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def zip_dir(src_dir: Path, zip_path: Path) -> None:
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in src_dir.rglob("*"):
            if path.is_file():
                zf.write(path, path.relative_to(src_dir))


def zip_files(files: list[Path], zip_path: Path, base_dir: Path) -> None:
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in files:
            zf.write(path, path.relative_to(base_dir))


def file_sha256(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_maintenance_kit(dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)

    def ignore(_dir: str, names: list[str]) -> set[str]:
        ignored = {
            "cache",
            "__pycache__",
        }
        return {name for name in names if name in ignored or name.endswith(".pyc")}

    shutil.copytree(MAINTENANCE_ROOT, dst, ignore=ignore)

    output = dst / "output"
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    write_text(
        output / "README.md",
        "이 폴더는 update_audit.bat 실행 후 업데이트 리포트가 생성되는 위치다.\n",
    )


def copy_public_docs(dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True, exist_ok=True)
    docs = LOCALIZATION_ROOT / "00_Project_Docs"
    for name in [
        "Glossary.md",
        "Translation_Tone_Guide.md",
        "Workflow_README.md",
        "Release_Packaging_Plan.md",
    ]:
        src = docs / name
        if src.exists():
            shutil.copy2(src, dst / name)


def copy_plugin_source(dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)

    def ignore(_dir: str, names: list[str]) -> set[str]:
        ignored = {"bin", "obj", ".vs", "__pycache__"}
        return {name for name in names if name in ignored or name.endswith(".pyc")}

    shutil.copytree(PLUGIN_SOURCE, dst, ignore=ignore)


def main() -> None:
    if not BEPINEX_TEMPLATE.exists():
        raise FileNotFoundError(f"BepInEx template not found: {BEPINEX_TEMPLATE}")
    if not PLUGIN_RELEASE_DLL.exists():
        raise FileNotFoundError(f"Build the plugin first: {PLUGIN_RELEASE_DLL}")

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    package_name = f"HXSS_KoreanPatch_{VERSION}_{stamp}"
    stage = PACKAGE_ROOT / "stage" / package_name
    output_zip = PACKAGE_ROOT / f"{package_name}.zip"

    PACKAGE_ROOT.mkdir(parents=True, exist_ok=True)
    copytree_clean(BEPINEX_TEMPLATE, stage)

    plugin_dst = stage / "BepInEx" / "plugins" / "HXSS.HuiWenFontReplacer"
    copy_required_file(PLUGIN_RELEASE_DLL, plugin_dst / "HXSS.HuiWenFontReplacer.dll")
    copy_required_file(LIVE_PLUGIN_DIR / "Shilla_HuiWen_CN_KR_Strict.ttf", plugin_dst / "Shilla_HuiWen_CN_KR_Strict.ttf")
    copy_required_file(LIVE_PLUGIN_DIR / "hardcoded_text.tsv", plugin_dst / "hardcoded_text.tsv")

    korean_patch_src = latest_lua_patch_dir()
    korean_patch_dst = plugin_dst / "KoreanPatch"
    if korean_patch_dst.exists():
        shutil.rmtree(korean_patch_dst)
    shutil.copytree(korean_patch_src, korean_patch_dst)

    write_text(stage / "BepInEx" / "config" / "hxss.huiwen-font-replacer.cfg", CONFIG_TEXT)
    write_text(stage / "README_KO.md", README_TEXT)
    write_text(
        stage / "CHANGELOG_KO.md",
        "- v0.1.3: GitHub Releases 수동 설치 ZIP 배포 기준 적용.\n",
    )
    copy_maintenance_kit(stage / "HXSS_Korean_Localization" / "MaintenanceKit")
    copy_public_docs(stage / "HXSS_Korean_Localization" / "00_Project_Docs")
    copy_plugin_source(stage / "HXSS_Korean_Localization" / "03_Font_Work" / "Font" / "HuiWenFontReplacer")

    for junk_name in ["collected_chinese.tsv", "lua_loader_trace.tsv", "language_call_trace.tsv"]:
        junk = plugin_dst / junk_name
        if junk.exists():
            junk.unlink()

    manifest = stage / "manifest.tsv"
    with manifest.open("w", encoding="utf-8", newline="\n") as f:
        f.write("path\tsize\n")
        for path in sorted(stage.rglob("*")):
            if path.is_file() and path != manifest:
                f.write(f"{path.relative_to(stage).as_posix()}\t{path.stat().st_size}\n")

    zip_dir(stage, output_zip)
    digest = file_sha256(output_zip)
    sha_file = PACKAGE_ROOT / f"{package_name}_SHA256.txt"
    write_text(sha_file, f"{digest}  {output_zip.name}\n")

    print(f"stage={stage}")
    print(f"zip={output_zip}")
    print(f"sha256={digest}")
    print(f"sha256_file={sha_file}")
    print(f"manifest={manifest}")


if __name__ == "__main__":
    main()
