#!/usr/bin/env python3
"""
Huaxia: Warring States XUnity translation workflow helper.

Commands:
  init      Create Text/Work files used by the workflow.
  scan      Extract newly collected source strings into Work/Unsorted_New.txt.
  classify  Split Unsorted_New.txt into candidate review files.
  apply     Merge reviewed Work/Ready_*.txt files into Text translation files.
  validate  Validate translation files for XUnity-safe formatting.
  report    Print progress counts.
"""

from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
GAME_ROOT = PROJECT_ROOT.parent
BASE_DIR = GAME_ROOT / "BepInEx" / "Translation" / "ko"
TEXT_DIR = BASE_DIR / "Text"
WORK_DIR = PROJECT_ROOT / "04_Legacy_BepInEx_Work" / "Work"
AUTO_FILE = TEXT_DIR / "_AutoGeneratedTranslations.txt"
TASK_FILE = WORK_DIR / "TASK.md"

TEXT_FILES = {
    "01": "01_Core_UI.txt",
    "02": "02_World_Terms_Names.txt",
    "03": "03_Items_Equipment.txt",
    "04": "04_Stats_Status_Attributes.txt",
    "05": "05_Combat_Skills_Talents.txt",
    "06": "06_Quest_Narrative.txt",
    "07": "07_Dialogue.txt",
    "99": "99_Fixes_Override.txt",
}

CANDIDATE_FILES = {
    "01": "Candidate_01_Core_UI.txt",
    "02": "Candidate_02_World_Terms_Names.txt",
    "03": "Candidate_03_Items_Equipment.txt",
    "04": "Candidate_04_Stats_Status_Attributes.txt",
    "05": "Candidate_05_Combat_Skills_Talents.txt",
    "06": "Candidate_06_Quest_Narrative.txt",
    "07": "Candidate_07_Dialogue_ContextUnknown.txt",
}

WORK_FILES = [
    "Unsorted_New.txt",
    "Validation_Report.txt",
    "Glossary.md",
    *CANDIDATE_FILES.values(),
]

GLOSSARY = """# Huaxia: Warring States Glossary

## 정기신 표기 정책

- 좁은 마름모 성별 UI: 男 / 女
- 정기신 UI/팝업: 정(精) / 기(氣) / 신(神)
- 설명 첫 등장: 정(精), 기(氣), 신(神) 병기
- 반복 설명: 정 / 기 / 신
- 气는 한국어 한자 관습에 맞춰 설명 병기 시 氣로 표기
- 신체/기운/정신처럼 풀어 번역하지 않음

法术=술법
技艺=기예
天赋=천부
精=정(精)
气=기(氣)
神=신(神)
技艺·精=기예·정(精)
技艺·气=기예·기(氣)
技艺·神=기예·신(神)
技艺 · 精=기예·정(精)
技艺 · 气=기예·기(氣)
技艺 · 神=기예·신(神)
门客=문객
宗族=씨족
五行=오행
相生=상생
相克=상극
九州=구주
异兽=이수
功绩=공적
俸禄=녹봉
"""

SUBSTITUTIONS = ""


@dataclass(frozen=True)
class Entry:
    source: str
    target: str
    line: str
    line_no: int
    path: Path


def read_lines(path: Path) -> list[str]:
    if not path.exists():
        return []
    return path.read_text(encoding="utf-8-sig", errors="replace").splitlines()


def write_lines(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = "\n".join(lines)
    if payload:
        payload += "\n"
    path.write_text(payload, encoding="utf-8")


def parse_entries(path: Path) -> tuple[list[Entry], list[tuple[int, str]]]:
    entries: list[Entry] = []
    bad: list[tuple[int, str]] = []
    for line_no, line in enumerate(read_lines(path), 1):
        if not line.strip():
            continue
        split_at = find_unescaped_equals(line)
        if split_at < 0:
            bad.append((line_no, line))
            continue
        source, target = line[:split_at], line[split_at + 1 :]
        entries.append(Entry(source, target, line, line_no, path))
    return entries, bad


def find_unescaped_equals(line: str) -> int:
    for index, char in enumerate(line):
        if char == "=" and (index == 0 or line[index - 1] != "\\"):
            return index
    return -1


def format_entry(source: str, target: str) -> str:
    return f"{source}={target}"


def manual_paths() -> list[Path]:
    return [TEXT_DIR / name for name in TEXT_FILES.values()]


def ready_paths() -> list[Path]:
    if not WORK_DIR.exists():
        return []
    return sorted(WORK_DIR.glob("Ready_*.txt"))


def ensure_structure() -> None:
    TEXT_DIR.mkdir(parents=True, exist_ok=True)
    WORK_DIR.mkdir(parents=True, exist_ok=True)

    for filename in TEXT_FILES.values():
        path = TEXT_DIR / filename
        if not path.exists():
            path.write_text("", encoding="utf-8")

    for filename in WORK_FILES:
        path = WORK_DIR / filename
        if not path.exists():
            if filename == "Glossary.md":
                path.write_text(GLOSSARY, encoding="utf-8")
            else:
                path.write_text("", encoding="utf-8")

    for filename in ("_Preprocessors.txt", "_Postprocessors.txt"):
        path = TEXT_DIR / filename
        if not path.exists():
            path.write_text("", encoding="utf-8")

    subst = TEXT_DIR / "_Substitutions.txt"
    if not subst.exists() or not subst.read_text(encoding="utf-8-sig", errors="replace").strip():
        subst.write_text(SUBSTITUTIONS, encoding="utf-8")


def applied_sources() -> set[str]:
    sources: set[str] = set()
    for path in manual_paths():
        entries, _ = parse_entries(path)
        sources.update(entry.source for entry in entries)
    return sources


def scan() -> None:
    ensure_structure()
    auto_entries, bad = parse_entries(AUTO_FILE)
    applied = applied_sources()

    seen: set[str] = set()
    new_lines: list[str] = []
    for entry in auto_entries:
        if entry.source in applied or entry.source in seen:
            continue
        seen.add(entry.source)
        new_lines.append(entry.line)

    write_lines(WORK_DIR / "Unsorted_New.txt", new_lines)

    if bad:
        write_lines(
            WORK_DIR / "Validation_Report.txt",
            [f"[AutoGenerated no '='] line {line_no}: {line}" for line_no, line in bad],
        )

    print(f"scan: {len(new_lines)} new entries written to {WORK_DIR / 'Unsorted_New.txt'}")


def contains_any(text: str, words: tuple[str, ...]) -> bool:
    return any(word in text for word in words)


def classify_source(source: str) -> str:
    stripped = source.strip()
    length = len(stripped)

    dialogue_words = (
        "你", "我", "吾", "咱", "阁下", "先生", "士子", "姑娘", "大人", "兄",
        "是否了解", "可否", "不知", "若想", "自然会", "留步",
    )
    quest_words = (
        "任务", "完成", "开启功能", "前往", "造访", "事件", "目标", "剧情",
        "经历", "外出前", "感谢您", "欢迎踏入", "诸位", "志士豪杰",
    )
    item_words = (
        "武器", "盔甲", "衣物", "法器", "坐骑", "道具", "货物", "装备", "材料",
        "丹", "剑", "弓", "弩", "矛", "戟", "盾", "刀", "斧", "冠", "靴",
    )
    stat_words = (
        "属性", "生命", "灵力", "体力", "耐力", "力量", "敏捷", "根骨", "悟性",
        "名望", "善名", "恶名", "相性", "状态", "抗性", "减免", "加成", "数值",
        "攻速", "杀伤", "暴击", "防御", "护甲", "可分配",
        "经验", "犯罪值", "好感度", "功绩", "声誉", "身份", "价值", "钱币", "产业",
    )
    combat_words = (
        "法术", "技能", "技艺", "天赋", "五行", "相生", "相克", "伤害", "攻击",
        "近战", "远程", "释放", "冷却", "增益", "减损", "驱散", "剑气", "命中",
        "敌军", "战斗", "战场", "冲锋", "兵卒", "士兵",
    )
    world_words = (
        "华夏", "九州", "宗族", "氏", "姓", "族群", "国家", "势力", "诸侯",
        "周室", "中原", "河洛", "豫州", "县令", "炎黄", "异兽", "门客",
    )
    ui_words = (
        "确定", "拒绝", "取消", "返回", "全部", "设置", "画面", "声音", "游戏",
        "公告", "选择", "显示", "隐藏", "开启", "关闭", "保存", "删除", "继续",
        "重置", "暂无", "当前", "等级", "详情",
    )

    if contains_any(stripped, combat_words):
        return "05"
    if contains_any(stripped, stat_words):
        return "04"
    if contains_any(stripped, item_words):
        return "03"
    if contains_any(stripped, quest_words):
        return "06"
    if contains_any(stripped, dialogue_words) and ("。" in stripped or "？" in stripped or "！" in stripped or "，" in stripped):
        return "07"
    if contains_any(stripped, world_words):
        return "02"
    if length <= 8 or contains_any(stripped, ui_words):
        return "01"
    if "。" in stripped or "？" in stripped or "！" in stripped:
        return "06"
    return "01" if length <= 12 else "06"


def classify() -> None:
    ensure_structure()
    source_path = WORK_DIR / "Unsorted_New.txt"
    entries, bad = parse_entries(source_path)

    buckets: dict[str, list[str]] = {key: [] for key in CANDIDATE_FILES}
    for entry in entries:
        buckets[classify_source(entry.source)].append(entry.line)

    for key, filename in CANDIDATE_FILES.items():
        write_lines(WORK_DIR / filename, buckets[key])

    if bad:
        report = [f"[Unsorted no '='] line {line_no}: {line}" for line_no, line in bad]
        write_lines(WORK_DIR / "Validation_Report.txt", report)

    counts = ", ".join(f"{key}:{len(lines)}" for key, lines in sorted(buckets.items()))
    print(f"classify: {counts}")


def target_for_ready(path: Path) -> Path | None:
    name = path.name
    match = re.match(r"Ready_(\d{2})_", name)
    if not match:
        return None
    key = match.group(1)
    filename = TEXT_FILES.get(key)
    return TEXT_DIR / filename if filename else None


def apply_ready() -> None:
    ensure_structure()
    report: list[str] = []
    total_added = 0
    total_updated = 0
    all_manual_sources = applied_sources()

    for ready in ready_paths():
        target_path = target_for_ready(ready)
        if target_path is None:
            report.append(f"[Apply skipped] Unknown Ready target: {ready.name}")
            continue

        ready_entries, bad = parse_entries(ready)
        for line_no, line in bad:
            report.append(f"[Apply skipped] {ready.name}:{line_no} has no '=': {line}")

        existing_entries, _ = parse_entries(target_path)
        existing_by_source = {entry.source: entry.target for entry in existing_entries}

        for entry in ready_entries:
            issues = validate_entry(entry)
            if issues:
                report.extend(f"[Apply skipped] {ready.name}:{entry.line_no}: {issue}" for issue in issues)
                continue

            is_override = target_path.name == TEXT_FILES["99"]
            if entry.source in all_manual_sources and entry.source not in existing_by_source and not is_override:
                report.append(
                    f"[Apply skipped] {ready.name}:{entry.line_no}: duplicate source already exists in another manual file: {entry.source}"
                )
                continue

            if entry.source in existing_by_source:
                existing_by_source[entry.source] = entry.target
                total_updated += 1
            else:
                existing_by_source[entry.source] = entry.target
                all_manual_sources.add(entry.source)
                total_added += 1

        merged = [format_entry(source, target) for source, target in existing_by_source.items()]
        write_lines(target_path, merged)

    if report:
        write_lines(WORK_DIR / "Validation_Report.txt", report)

    print(f"apply: added={total_added}, updated={total_updated}, warnings={len(report)}")


TAG_RE = re.compile(r"</?(?:color|size|align|margin|link|b|i)(?:\\?=[^>]*)?>", re.IGNORECASE)
VAR_RE = re.compile(r"\{\{[^{}]+\}\}|\{\d+\}|%[sdif]")
NUMBER_RE = re.compile(r"[+-]?\d+(?:\.\d+)?%?")

ALLOW_EXTRA_TARGET_NEWLINES = {
    "全部随机",
    "重置头部",
    "随机头部",
    "重置头发",
    "随机头发",
    "重置胡须",
    "随机胡须",
    "重置眉毛",
    "随机眉毛",
    "重置眼睛",
    "随机眼睛",
    "重置身形",
    "随机身形",
    "重置皮肤",
    "随机皮肤",
    "重置声音",
    "随机声音",
}


def multiset(values: list[str]) -> Counter[str]:
    return Counter(values)


def validate_entry(entry: Entry) -> list[str]:
    issues: list[str] = []
    source = entry.source
    target = entry.target

    if not source:
        issues.append("empty source")
    if not target:
        issues.append("empty translation")

    if source.count(r"\n") != target.count(r"\n") and source not in ALLOW_EXTRA_TARGET_NEWLINES:
        issues.append(f"literal \\n count mismatch source={source.count(r'\\n')} target={target.count(r'\\n')}")

    source_tags = TAG_RE.findall(source)
    target_tags = TAG_RE.findall(target)
    if multiset(source_tags) != multiset(target_tags):
        issues.append("rich text tag mismatch")

    source_vars = VAR_RE.findall(source)
    target_vars = VAR_RE.findall(target)
    if multiset(source_vars) != multiset(target_vars):
        issues.append("variable placeholder mismatch")

    source_numbers = NUMBER_RE.findall(source)
    target_numbers = NUMBER_RE.findall(target)
    if multiset(source_numbers) != multiset(target_numbers):
        issues.append("number/percent token mismatch")

    return issues


def validate_files() -> None:
    ensure_structure()
    report: list[str] = []
    seen: dict[str, Path] = {}

    paths = manual_paths() + ready_paths()
    for path in paths:
        entries, bad = parse_entries(path)
        for line_no, line in bad:
            report.append(f"[No '='] {path.relative_to(BASE_DIR)}:{line_no}: {line}")
        for entry in entries:
            for issue in validate_entry(entry):
                report.append(f"[{issue}] {path.relative_to(BASE_DIR)}:{entry.line_no}: {entry.line}")

            if path in manual_paths():
                previous = seen.get(entry.source)
                is_allowed_override = previous is not None and (
                    path.name == TEXT_FILES["99"] or previous.name == TEXT_FILES["99"]
                )
                if previous is not None and not is_allowed_override:
                    report.append(
                        f"[duplicate source] {path.relative_to(BASE_DIR)}:{entry.line_no} duplicates {previous.relative_to(BASE_DIR)}: {entry.source}"
                    )
                else:
                    seen[entry.source] = path

    write_lines(WORK_DIR / "Validation_Report.txt", report)
    print(f"validate: {len(report)} issue(s), report={WORK_DIR / 'Validation_Report.txt'}")


def count_entries(path: Path) -> int:
    entries, _ = parse_entries(path)
    return len(entries)


def report() -> None:
    ensure_structure()
    auto_entries, auto_bad = parse_entries(AUTO_FILE)
    auto_unique = len({entry.source for entry in auto_entries})
    applied = applied_sources()
    unsorted = count_entries(WORK_DIR / "Unsorted_New.txt")
    validation_issues = len([line for line in read_lines(WORK_DIR / "Validation_Report.txt") if line.strip()])

    print("HXSS localization report")
    print(f"auto entries: {len(auto_entries)}")
    print(f"auto unique sources: {auto_unique}")
    print(f"auto malformed lines: {len(auto_bad)}")
    print(f"manual applied sources: {len(applied)}")
    print(f"unsorted new entries: {unsorted}")

    print("manual files:")
    for key, filename in TEXT_FILES.items():
        print(f"  {key} {filename}: {count_entries(TEXT_DIR / filename)}")

    print("candidate files:")
    for key, filename in CANDIDATE_FILES.items():
        print(f"  {key} {filename}: {count_entries(WORK_DIR / filename)}")

    print(f"validation issues: {validation_issues}")
    print(f"task file: {TASK_FILE}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Huaxia: Warring States localization workflow helper")
    parser.add_argument("command", choices=["init", "scan", "classify", "apply", "validate", "report"])
    args = parser.parse_args()

    if args.command == "init":
        ensure_structure()
        print(f"init: structure ready under {BASE_DIR}")
    elif args.command == "scan":
        scan()
    elif args.command == "classify":
        classify()
    elif args.command == "apply":
        apply_ready()
    elif args.command == "validate":
        validate_files()
    elif args.command == "report":
        report()


if __name__ == "__main__":
    main()
